<?php

namespace AppBundle\Repository;

/**
 * degresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class degresRepository extends \Doctrine\ORM\EntityRepository
{
}
